// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chptgetdjuziglndibhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNocHRnZXRkanV6aWdsbmRpYmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjM3MjAsImV4cCI6MjA2MjQ5OTcyMH0.is374cBbK5wIgF67ePimmuDYXSM5U_79j2qkayWAZDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);